name: Publish Docker Images Daily

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * *'

jobs:
  publish_to_dockerhub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: obscuritylabs/asciidoctor-pdf
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
  publish_to_github:
    name: Publish to Github
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Github Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: obscuritylabs/asciidoctor-pdf/asciidoctor-pdf
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
